# Generated by Django 4.1.2 on 2023-04-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='frontpage',
            field=models.BooleanField(default=False),
        ),
    ]
